version: '3'
services:
  ubuntu:
    image: jupyter:latest
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: jupyter
    hostname: jupyter
    ports:
      - '8888:8888'
    volumes:
      - ./data:/data
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
